### ISSUE TITLE
InfosetChatVisitor customFields parameter

### ISSUE THREAD

**Issue by HalitGumus** [Infoset/infoset-ios#2]
When we examined your web product, I saw the customFields parameter as follows. But I didn't see such a parameter for iOS. This field is needed to send us an customId we want. Can you help me?

https://infoset.app/help/tr/articles/145-sohbet-aracinizi-web-uygulamaniza-entegre-edin-giris-yapmis-kullanicilariniz-icin

```
InfosetChat('boot', {
  widget: {
    apiKey: '<api_key>',
  },
  visitor: {
    id: '<user_id>',
    firstName: 'Ad',
    lastName: 'Soyad',
    email: 'eposta@kullanici.com',
    phone: '+905554443322',
    photoUrl: 'https://sirket.com/abc.png',
    createdAt: '<iso_format_tarih>',
    company: 'Sirket',
    customFields: {
      ornekVeriAlani: 'ornekDeger',
      ornekVeriAlani2: 1234567,
    },
  },
});
```

**Comment by onurcskun** [comment]
Hi, this field related with custom fields under the dashboard `https://dashboard.infoset.app/settings/general?tab=dataFields`

There is `contact` tab under this link, and you can send fields that you added to fields. There is no id,
Keys are name of your field like in the attachment. It can be spaced like “custom field name”
Doesn’t matter. If you have any other question please contact with ***@***.*** and our customer support will in touch with you.


Sevgiler,

Onur Coşkun
Software Engineer at Infoset
A: Ata Plaza K:3, Maltepe/İstanbul
T: +90 850 450 0040

**Comment by HalitGumus** [comment]
@onurcskun Selam,

Cevap için teşekkürler.

Android ve Web projelerinde InfosetChatVisitor için direk customField diye bir parametre alanı var, oraya istediğimiz parametreleri ekleyip backend tarafında kullanmayı düşünüyorduk. Diğer platformlar geliştirmeyi yaptı ama ios için böyle bir alan göremedim. Nasıl yapabiliriz.

SWIFT_CLASS("_TtC7Infoset18InfosetChatVisitor")
@interface InfosetChatVisitor : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
@property (nonatomic, readonly, copy) NSString * _Nullable email;
@property (nonatomic, readonly, copy) NSString * _Nullable phone;
@property (nonatomic, readonly, copy) NSString * _Nullable photoUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable userHash;
@property (nonatomic, readonly, copy) NSString * _Nullable createdAt;
@property (nonatomic, readonly, copy) NSString * _Nullable company;
- (nonnull instancetype)initWithId:(NSString * _Nullable)id firstName:(NSString * _Nullable)firstName lastName:(NSString * _Nullable)lastName email:(NSString * _Nullable)email phone:(NSString * _Nullable)phone photoUrl:(NSString * _Nullable)photoUrl userHash:(NSString * _Nullable)userHash createdAt:(NSString * _Nullable)createdAt company:(NSString * _Nullable)company OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

**Comment by onurcskun** [comment]
Merhabalar tekrardan,

Haklısınız ekibe iletiyorum, en kısa sürede eklenip versiyon çıkılacak.

Sevgiler,

Onur Coşkun
Software Engineer at Infoset
A: Ata Plaza K:3, Maltepe/İstanbul
T: +90 850 450 0040

**Comment by onurcskun** [comment]
1.6.0 surumu canlıya alindi rica etsem tekrar deneyebilir misiniz dictionary olarak [string, string] vermeniz yeterli visitor objesi içerisinde.

Sevgiler,

Onur Coşkun
Software Engineer at Infoset
A: Ata Plaza K:3, Maltepe/İstanbul
T: +90 850 450 0040

**Comment by HalitGumus** [comment]
Pod üzerinden 1.6.0 sürümünü aldım. Ama aşağıdaki gibi halen hata veriyor. @onurcskun 

<img width="1013" alt="Screenshot 2023-11-30 at 9 48 25 AM" src="https://github.com/Infoset/infoset-ios/assets/17872594/e3abe898-a575-4612-bad4-e2b2f426a887">

**Comment by onurcskun** [comment]
Bunun degismis olmasi lazimdi, kontrol edip tekrar haber verecegim sizlere.

**Comment by onurcskun** [comment]
@HalitGumus 1.6.1 versiyonu cikildi, bilginize.

**Comment by HalitGumus** [comment]
1.6.1 versionu ile denediğimde çalıştı. Elinize sağlık.

Teşekkürler @onurcskun 
İyi çalışmalar
